"""phase 3 schema

Revision ID: 4cb5324d6e1e
Revises: 000d90328da3
Create Date: 2026-09-28 16:18:50.787062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb5324d6e1e'
down_revision = '000d90328da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # §8.3 CHECK constraints and the partial unique index on invoices are added
    # by hand below: Alembic autogenerate cannot see them from SQLite models, but
    # §8.1 still requires the DDL to carry them.
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('project_address', sa.Text(), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_archived_at'), ['archived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_name'), ['name'], unique=False)

    op.create_table('company_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), server_default='Ruchita Interiors', nullable=False),
    sa.Column('tagline', sa.String(length=200), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=12), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('default_gst_bp', sa.Integer(), server_default='1800', nullable=False),
    sa.Column('default_validity_days', sa.Integer(), server_default='15', nullable=False),
    sa.Column('quotation_prefix', sa.String(length=12), server_default='QTN', nullable=False),
    sa.Column('invoice_prefix', sa.String(length=12), server_default='INV', nullable=False),
    sa.Column('bank_account_name', sa.String(length=200), nullable=True),
    sa.Column('bank_account_number', sa.String(length=64), nullable=True),
    sa.Column('bank_name', sa.String(length=200), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=11), nullable=True),
    sa.Column('bank_branch', sa.String(length=200), nullable=True),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('signatory_name', sa.String(length=200), nullable=True),
    sa.Column('footer_text', sa.String(length=500), nullable=True),
    sa.Column('item_categories', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('units', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('numbering_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=16), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_type', 'year', name='uq_numbering_doc_year')
    )
    op.create_table('terms_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('client_snapshot', sa.JSON(), nullable=True),
    sa.Column('quotation_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('discount_type', sa.String(length=8), nullable=True),
    sa.Column('discount_bp', sa.Integer(), nullable=True),
    sa.Column('discount_fixed_paise', sa.Integer(), nullable=True),
    sa.Column('gst_bp', sa.Integer(), nullable=True),
    sa.Column('other_charges_label', sa.String(length=200), server_default='Other Charges', nullable=True),
    sa.Column('other_charges_paise', sa.Integer(), nullable=True),
    sa.Column('subtotal_paise', sa.Integer(), nullable=True),
    sa.Column('discount_paise', sa.Integer(), nullable=True),
    sa.Column('gst_paise', sa.Integer(), nullable=True),
    sa.Column('grand_total_paise', sa.Integer(), nullable=True),
    sa.Column('terms_text', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number'),
    sa.CheckConstraint("status IN ('draft','sent','approved','rejected','converted')", name='ck_quotations_status')
    )
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotations_client_id'), ['client_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('client_snapshot', sa.JSON(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('discount_type', sa.String(length=8), nullable=True),
    sa.Column('discount_bp', sa.Integer(), nullable=True),
    sa.Column('discount_fixed_paise', sa.Integer(), nullable=True),
    sa.Column('gst_bp', sa.Integer(), nullable=True),
    sa.Column('other_charges_label', sa.String(length=200), nullable=True),
    sa.Column('other_charges_paise', sa.Integer(), nullable=True),
    sa.Column('subtotal_paise', sa.Integer(), nullable=True),
    sa.Column('discount_paise', sa.Integer(), nullable=True),
    sa.Column('gst_paise', sa.Integer(), nullable=True),
    sa.Column('grand_total_paise', sa.Integer(), nullable=True),
    sa.Column('terms_text', sa.Text(), nullable=True),
    sa.Column('bank_snapshot', sa.JSON(), nullable=True),
    sa.Column('signatory_name', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number'),
    sa.CheckConstraint("status IN ('draft','issued','cancelled')", name='ck_invoices_status')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_quotation_id'), ['quotation_id'], unique=False)
        # §8.3: one active invoice per quotation — a cancelled invoice frees its
        # quotation for re-invoicing, which only a partial UNIQUE index can
        # express in SQLite.
        batch_op.create_index(
            'uq_invoices_active_quotation',
            ['quotation_id'],
            unique=True,
            sqlite_where=sa.text("status != 'cancelled'"),
        )

    op.create_table('quotation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('qty_milli', sa.Integer(), server_default='0', nullable=True),
    sa.Column('rate_paise', sa.Integer(), server_default='0', nullable=True),
    sa.Column('line_total_paise', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint('qty_milli >= 0', name='ck_quotation_items_qty_nonnegative'),
    sa.CheckConstraint('rate_paise >= 0', name='ck_quotation_items_rate_nonnegative')
    )
    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.create_index('ix_quotation_items_quotation_position', ['quotation_id', 'position'], unique=False)

    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('qty_milli', sa.Integer(), server_default='0', nullable=True),
    sa.Column('rate_paise', sa.Integer(), server_default='0', nullable=True),
    sa.Column('line_total_paise', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint('qty_milli >= 0', name='ck_invoice_items_qty_nonnegative'),
    sa.CheckConstraint('rate_paise >= 0', name='ck_invoice_items_rate_nonnegative')
    )
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.create_index('ix_invoice_items_invoice_position', ['invoice_id', 'position'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint('amount_paise > 0', name='ck_payments_amount_positive'),
    sa.CheckConstraint("method IN ('cash','upi','bank_transfer','cheque','card','other')", name='ck_payments_method')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))

    op.drop_table('payments')
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_index('ix_invoice_items_invoice_position')

    op.drop_table('invoice_items')
    with op.batch_alter_table('quotation_items', schema=None) as batch_op:
        batch_op.drop_index('ix_quotation_items_quotation_position')

    op.drop_table('quotation_items')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_quotation_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_client_id'))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index('uq_invoices_active_quotation')

    op.drop_table('invoices')
    with op.batch_alter_table('quotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotations_client_id'))

    op.drop_table('quotations')
    op.drop_table('terms_conditions')
    op.drop_table('numbering_counters')
    op.drop_table('company_settings')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_name'))
        batch_op.drop_index(batch_op.f('ix_clients_archived_at'))

    op.drop_table('clients')
    # ### end Alembic commands ###
