"""phase 8 payment qr code

Revision ID: a7c4e19b2d80
Revises: 4cb5324d6e1e
Create Date: 2026-09-29 22:10:00.000000

Adds `company_settings.payment_qr_path`, the Settings-managed UPI QR code that
Phase 8 renders on invoice documents.

The column is deliberately NOT part of the `invoices.bank_snapshot`: the QR is a
live payment instruction rather than a frozen document fact, so it is read from
Settings at render time and never copied onto an issued invoice.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c4e19b2d80'
down_revision = '4cb5324d6e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite cannot ALTER TABLE ADD COLUMN through plain `op.add_column` in every
    # code path Alembic generates, so the change goes through batch mode, which
    # rewrites the table. This matches the phase 3 migration's use of
    # `batch_alter_table` for every index.
    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_qr_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.drop_column('payment_qr_path')

    # ### end Alembic commands ###
